# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import re

def read_matrix(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()[1:]
        matrix = [line.strip() for line in lines]
    return matrix

def decode_matrix(matrix):
    decoded_text = ""
    for row in matrix:
        decoded_text += row
    decoded_text = re.sub(r'[^a-zA-Z\s]', '', decoded_text)
    return decoded_text

file_path = "matrix.txt"

matrix = read_matrix(file_path)
decoded_text = decode_matrix(matrix)

print("Output:", decoded_text)